### ISSUE TITLE
ClassCheckIn 系統架構

### ISSUE THREAD

**Issue by timchengx** [HackerSir/ClassCheckIn#1]
還沒想到好方法來搬 issues
所以先附上連結

https://bitbucket.org/hackersir/classcheckin/issue/1

**Comment by danny50610** [comment]
[苦力搬 Issue]

(根據社長的想法)
點名系統分成三個部分：
1. 手機 (當 sensor 用)
2. 電腦 (紀錄簽到資料)
3. 伺服器 (儲存簽到資料)
細節還沒確定

而且還有 Repository 切割的問題
(就是這三個部分都要放在這個 Repository 嗎？)
(^^^^另開issue)

但時間緊迫
目前打算先只開發 1.2 部分

**Comment by danny50610** [comment]
[Tim Cheng]

根據討論與我的想法 可以設計以下成兩種方式
1. 首先 社員要先註冊 有其資料(姓名, 系級, email, 卡號)... 存在網站上 要簽到時 Android手機要去抓本次上課日期資料及社員的卡片id清單 來進行簽到(離線, 因為學校網路不穩定不建議採用online)
2. 還是如同 1 但是簡單化 Android手機每次只抓卡號 然後上傳到網站上 所以的判斷工作都由網站來處理

問題等待釐清:
       註冊資料(網站上的資料庫的table要怎麼設計?)

設計1的Android手機問題 Android手機要把資料抓下來 那網站提供的api要怎麼設計 然後抓下來的資料格式是甚麼? Android手機在簽到後 要顯示甚麼資料(要判斷是否為社員嗎?)(要顯示刷卡人的資訊嗎?)

設計1 2 都有的問題 \* Android手機完成刷卡後 要怎樣把資料上傳到網站上? 上傳的資料格式是甚麼? 網站上的資料庫tables要怎麼設計?

**Comment by vongola12324** [comment]
兩種方案其實我覺得都可以，方法一的話就是在手機上新增課程時，就直接去資料庫dump一份資料下來；法二就更簡單了，資料丟出去然後沒了。     

註冊資料的話，Table設計是指資料庫格式嗎？如果是的話應該像這樣....    
- ID (INT)  
- NID (VARCHAR)  
- Name (VARCHAR)  
- 系級 (VARCHAR)  
- 信箱 (TEXT)  

如果使用者沒填信箱則自動用NID@mail.fcu.edu.tw

但如果真要比較法一跟法二，因為我們手機需要顯示你是不是社員，不是的話要到旁邊人工簽到(雖然理應不會有這種狀況)，所以可能法一會比較適合，再來API的話，其實我沒想那麼多耶，我原本是想說直接連到網頁之後先交涉驗證碼，如果通過了就由網頁把資料庫dump成json或者是比較好解析的格式，傳給手機，手機看是要直接讀取還是把他轉成SQLite再來跑這樣。

再來是把資料上傳的話，我的想法就是反向過去就可以了，可能就是封裝json再丟過去之類的....，那關於table的話大概是這樣：
- ID (INT)
- 日期 (DATE)
- NID (VARCHAR)

我覺得這樣就行了，畢竟如果有需要資料分析的話應該可以根據NID去爬社員資料庫不是嗎？

最後，可能需要一個額外的功能，社員資料需要能夠匯出成excel格式，或是excel可以閱讀的格式。

**Comment by jyhsu2000** [comment]
比較偏好方法一
只要在「最後一人註冊後」和「上課前」這段時間，從Android發出一次同步請求
便能在該次課程正常簽到點名
不過無論是一或二
都需要制訂API
如：
- 取得名單資料
  - Send: Date
  - Get: Date、List(NID、Name...)
- 發送點名資料
  - Send: Date、List(NID)
  - Get: Result code of Result message

如果如同以往使用Laravel的話
直接採用JSON封裝即可

至於網站資料表（或許該說是模型架構）
以最簡單的方式，可以分為以下幾個表
參考看看唄
- users
  - ID（INT(10)、AI、PK）
  - NID（VARCHAR(8)）
  - email（TEXT）
  - Password（VARCHAR(64)）
  - Name（VARCHAR(20)）
  - 系級（VARCHAR(20)）
  - Laravel timestamps（create_at、update_at）
- courses
  - ID（INT(10)、AI、PK）
  - Date（Date）
  - Subject（VARCHAR(20)）
  - Lecturer（VARCHAR(20)）
  - Laravel timestamps（create_at、update_at）
- signin
  - ID（INT(10)、AI、PK）
  - user_id（INT(10)）
  - course_id（INT(10)）
  - Laravel timestamps（create_at、update_at）

不過...
網站部分...
算是電腦還是伺服器？
還是直接從社網那邊去做？

**Comment by jyhsu2000** [comment]
話說...
手機那邊
能直接把卡號轉為NID嗎？

**Comment by danny50610** [comment]
[Tim Cheng]
沒有資料 不行

**Comment by vongola12324** [comment]
@jyhsu2000 學長你是指哪時候呢？刷卡的時候嗎？  
刷卡的時候只讀取資料庫有的人，這樣應該會有資料吧？
另外想問問 laravel timestamp是哪種format?

@gnehcmit 什麼不行?

**Comment by jyhsu2000** [comment]
@gnehcmit 如果手機刷到新卡片時，請使用者輸入學號呢？
學號跟卡號的對應由網站管理，如何？

@vongola12324 兩者都是timestamp
不過這並不重要，不知道也無所謂
畢竟正確來說
Laravel的資料表建置是透過[migrations](http://laravel.tw/docs/5.0/migrations)完成
在裡面是使用[結構生成器](http://laravel.tw/docs/5.0/schema)
只需要`$table->timestamps();`即可直接產生laravel的timestamps
其餘所有欄位亦然
根本不需要接觸到SQL那層的具體架構規劃

**Comment by danny50610** [comment]
[Tim Cheng]

@jyhsu2000  這樣可以
有關API制定以及相關資料結構就你們底定後跟我說 我再來想辦法界接

**Comment by jyhsu2000** [comment]
@gnehcmit OK
那格式就暫訂為JSON
細節就...決定之後再寫文件吧

**Comment by jyhsu2000** [comment]
網站架構
轉移到[HackerWebSite](https://github.com/HackerSir/HackerWebSite)專案繼續討論：
[Issue#1 模型架構](https://github.com/HackerSir/HackerWebSite/issues/1)
